service:
- docker

env:
  global:
  - DOCKER_USERNAME=sbrunner
  - secure: "IREaUtBn1mm6IhCqIFvJkH2LsDl9/VtS/r2sHzSVBPhuZozjrfk1029g8fwfjgHbEZ+4/ZleYERybf76oe+lCJoHglS+DGMYFmWSAEW7F2wBpqKxYNmmlwgx9R9LZ3Y3XnRs836MIftwPxr7N3w1rv/QPZ+wUWd2q+VkpVQ16vtuaBZ8EBTQ4JsPQb32j+9c/ic7rtVSZwV7pMk854bLCPwnvDAYz16f1LIKD8kvlgXpfP3xvBuOIzmSi8KCCaLelDmdWDVbaMvGl/Dq1M4B0+lRUghRaMmL6kAANhhYMKhAiUDuXqashqSxOZA3UwNWXekpSOs+wnWBYcnCGjTNL/GkN3YLc5UsuymZzkdwZsMI67qSH5Xujnx2EJ/IkJLKrJG2oMLdZkU2hm14muSYN4lt2ScVB3/Zs1gjAoag0BYYAIzXncpYhvGOhcE8gmJDXFubRj3wf5Zv90eOBobcE2mILqwCoHmqmXkNCr8zpIzRY5kIIFA0MGSTstiL2CaUUWE4b8Tm1ydSBE9G3MHLz283gDCU7/9R5jrzEWiTThZR5Ieidr7jGlIcFmgsvpVCaJ2/xvqxG3iHon1cHkYJZZF4M1vrLG3oJ/SZcN4bkWshQhEo0yiN+T9J3ZoOopcOTLAig7CJ2bHl9w8QvEwoUJDr+mYYXtffnQUsGJprlBg="

install:
- docker build .

deploy:
- provider: script
  script: publish-docker
  on:
    repo: camptocamp/docker-python-gis
    tags: true
- provider: script
  script: publish-docker
  on:
    repo: camptocamp/docker-python-gis
    all_branches: true
    condition: '"${TRAVIS_PULL_REQUEST}" = false'
