#!/bin/bash

docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

IMAGE=python-gis

if [ "${TRAVIS_TAG}" != "" ]
then
    docker tag camptocamp/${IMAGE}:latest camptocamp/${IMAGE}:${TRAVIS_TAG}
    docker push camptocamp/${IMAGE}:${TRAVIS_TAG}
elif [ "${TRAVIS_BRANCH}" != "master" ]
then
    docker tag camptocamp/${IMAGE}:latest camptocamp/${IMAGE}:${TRAVIS_BRANCH}
    docker push camptocamp/${IMAGE}:${TRAVIS_BRANCH}
else
    echo "Building master should not happen"
    exit 1
fi
