---

version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: 3.7-ubuntu20.04
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: 3.7-buster
