---

version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: 3.6-stretch
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: '3.6'
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: '3.5'

