---

name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-18.04
    name: Continuous integration
    timeout-minutes: 30

    env:
      SUMMON_PROVIDER: /usr/local/bin/gopass

    steps:
      - uses: actions/checkout@v1
      - run: docker build .
      - run: docker build --target=runner --tag=camptocamp/python-gis .

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GITHUB_GOPASS_CI_TOKEN}}
        if: github.repository == 'camptocamp/docker-python-gis'
      - run: mkdir -p ~/.docker
        if: github.repository == 'camptocamp/docker-python-gis'
      - run: |
          summon --yaml '
            TOKEN: !var gs/ci/dockerhub/token
          ' bash -c 'envsubst < ci/docker-config.json.tmpl > ~/.docker/config.json'
        if: github.repository == 'camptocamp/docker-python-gis'
      - name: Publish to Docker hub
        run: ci/publish ubuntu-18.04
        if: github.repository == 'camptocamp/docker-python-gis'
