---

name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-18.04
    name: Continuous integration
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v1
      - run: docker build .
      - run: docker build --target=runner --tag=camptocamp/python-gis .
